name: hds-gateway-express

services:
  hds-gateway-express:
    build: .
    image: sonexus/hds-gateway-express:latest
    container_name: docker-hds-gateway-express

    restart: unless-stopped

    environment:
      POSTGRES_HOST: docker-hds-metadata-postgresql
      POSTGRES_PORT: "5432"
      POSTGRES_DB: sonexus
      POSTGRES_USER: sonexus
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Set POSTGRES_PASSWORD}

    networks:
      - sonexus-management

    ports:
      - "3001:3000"

    volumes:
      - ../Dashboard:/app/dashboard:ro

networks:
  sonexus-management:
    external: true
