name: hds-webtorrent-seeder

services:
  hds-webtorrent-seeder:
    image: sonexus/hds-webtorrent-seeder:latest

    build:
      context: .

    container_name: docker-hds-webtorrent-seeder

    environment:
      DEBUG: webtorrent*
      TEST_MODE: "true"

    restart: unless-stopped

    networks:
      - docker-network-webtorrent

    ports:
      - "3000:3000"
      - "40245:40245"
      - "40245:40245/udp"

    volumes:
      - ../../storage/music:/data

networks:
  docker-network-webtorrent:
    external: true
