services:
  hds-ipfs-source-kubo:
    image: ipfs/kubo:latest
    container_name: docker-hds-ipfs-source-kubo

    restart: unless-stopped

    networks:
      - docker-network-ipfs

    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"

    volumes:
      - ../../storage/ipfs:/data/ipfs

networks:
  docker-network-ipfs:
    external: true
